var searchData=
[
  ['i_20o_20expander_20module_0',['I O Expander Module',['../group__MCP23016.html',1,'MCP23016 16-bit I2C/SMBus I/O Expander Module'],['../group__PCA9554.html',1,'PCA9554 8-bit I2C/SMBus I/O Expander Module']]],
  ['i2c_20smbus_20i_20o_20expander_20module_1',['I2C SMBus I O Expander Module',['../group__MCP23016.html',1,'MCP23016 16-bit I2C/SMBus I/O Expander Module'],['../group__PCA9554.html',1,'PCA9554 8-bit I2C/SMBus I/O Expander Module']]],
  ['ics_2',['Peripheral ICs',['../group__PERIPH__IC.html',1,'']]],
  ['in_20scb_20scnscb_3',['System Controls not in SCB (SCnSCB)',['../group__CMSIS__SCnSCB.html',1,'']]],
  ['ina220_20high_20or_20low_20side_20bidirectional_20current_20and_20power_20monitor_4',['INA220 - High- or Low-Side, Bidirectional Current and Power Monitor',['../group__INA220.html',1,'']]],
  ['ina220_20registers_5',['INA220 Registers',['../group__INA220__REGS.html',1,'']]],
  ['ina3221_20high_20or_20low_20side_20bidirectional_20current_20and_20power_20monitor_6',['INA3221 - High- or Low-Side, Bidirectional Current and Power Monitor',['../group__INA3221.html',1,'']]],
  ['ina3221_20registers_7',['INA3221 Registers',['../group__INA3221__REGS.html',1,'']]],
  ['instruction_20interface_8',['CMSIS Core Instruction Interface',['../group__CMSIS__Core__InstructionInterface.html',1,'']]],
  ['instructions_20reference_9',['Functions and Instructions Reference',['../group__CMSIS__Core__FunctionInterface.html',1,'']]],
  ['instrumentation_20trace_20macrocell_20itm_10',['Instrumentation Trace Macrocell (ITM)',['../group__CMSIS__ITM.html',1,'']]],
  ['intelligent_20platform_20management_20interface_11',['IPMI - Intelligent Platform Management Interface',['../group__IPMI.html',1,'']]],
  ['interface_12',['Interface',['../group__CMSIS__Core__InstructionInterface.html',1,'CMSIS Core Instruction Interface'],['../group__IPMI.html',1,'IPMI - Intelligent Platform Management Interface']]],
  ['interface_20tpi_13',['Trace Port Interface (TPI)',['../group__CMSIS__TPI.html',1,'']]],
  ['interrupt_20controller_20nvic_14',['Nested Vectored Interrupt Controller (NVIC)',['../group__CMSIS__NVIC.html',1,'']]],
  ['intrinsics_15',['CMSIS SIMD Intrinsics',['../group__CMSIS__SIMD__intrinsics.html',1,'']]],
  ['ipmi_20commands_16',['IPMI Commands',['../group__IPMI__CMD.html',1,'']]],
  ['ipmi_20commands_20application_200x06_17',['IPMI Commands - Application (0x06)',['../group__IPMI__APP__CMD.html',1,'']]],
  ['ipmi_20commands_20brigde_200x02_18',['IPMI Commands - Brigde (0x02)',['../group__IPMI__BRIGDE__CMD.html',1,'']]],
  ['ipmi_20commands_20chassis_200x00_19',['IPMI Commands - Chassis (0x00)',['../group__IPMI__CHASSIS__CMD.html',1,'']]],
  ['ipmi_20commands_20custom_200x32_20',['IPMI Commands - Custom (0x32)',['../group__IPMI__CUSTOM__CMD.html',1,'']]],
  ['ipmi_20commands_20picmg_200x2c_21',['IPMI Commands - PICMG (0x2C)',['../group__IPMI__PICMG__CMD.html',1,'']]],
  ['ipmi_20commands_20sensor_200x04_22',['IPMI Commands - Sensor (0x04)',['../group__IPMI__SENSOR__CMD.html',1,'']]],
  ['ipmi_20commands_20storage_200x0a_23',['IPMI Commands - Storage (0x0A)',['../group__IPMI__STORAGE__CMD.html',1,'']]],
  ['ipmi_20commands_20storage_200x0c_24',['IPMI Commands - Storage (0x0C)',['../group__IPMI__TRANSPORT__CMD.html',1,'']]],
  ['ipmi_20completion_20codes_25',['IPMI Completion Codes',['../group__IPMI__CC.html',1,'']]],
  ['ipmi_20intelligent_20platform_20management_20interface_26',['IPMI - Intelligent Platform Management Interface',['../group__IPMI.html',1,'']]],
  ['ipmi_20net_20functions_27',['IPMI Net Functions',['../group__IPMI__NETFN.html',1,'']]],
  ['ipmi_20oem_20commands_28',['IPMI OEM Commands',['../group__AFC__TIMING__IPMI__OEM.html',1,'AFC-Timing IPMI OEM Commands'],['../group__AFC__V4__0__IPMI__OEM.html',1,'AFCv4.0 IPMI OEM Commands']]],
  ['itm_29',['Instrumentation Trace Macrocell (ITM)',['../group__CMSIS__ITM.html',1,'']]],
  ['itm_20functions_30',['ITM Functions',['../group__CMSIS__core__DebugFunctions.html',1,'']]]
];
