#ifndef I2C_MAPPING_H_
#define I2C_MAPPING_H_

#include "i2c.h"

#define I2CMODE_POOLING         1
#define I2CMODE_INTERRUPT       0
#define SPEED_100KHZ            100000

// BUS_ID
// 0 - FMC1
// 1 - FMC2
// 3 - CPU_ID
//
///////////////////////

#define RTM_MUX_BUS_NUM         10

enum
{
  I2C_BUS_UNKNOWN_ID = 0x00,
  I2C_BUS_FMC1_ID,
  I2C_BUS_SFP1_ID,
  I2C_BUS_SFP2_ID,
  I2C_BUS_CLOCK_ID,
  I2C_BUS_PM_ID,
  I2C_BUS_SENS_ID,
  I2C_BUS_RTM_ID,
  I2C_BUS_MUX_ID,
  #ifdef MODULE_RTM
  I2C_BUS_RTM_MEZ0_0_ID,
  I2C_BUS_RTM_MEZ0_1_ID,
  I2C_BUS_RTM_MEZ1_0_ID,
  I2C_BUS_RTM_MEZ1_1_ID,
  I2C_BUS_RTM_SI5324_ID,
  I2C_BUS_RTM_TMP_ID,
  I2C_BUS_RTM_EXAR_ID,
#endif
  I2C_BUS_CPU_ID,
  I2C_BUS_FPGA_ID,
  I2C_BUS_CNT
};

enum
{
  /* Chips on AMC */
  CHIP_ID_MUX_MMC = 0,
  CHIP_ID_MUX_FPGA,
  CHIP_ID_FMC1_EEPROM,
  CHIP_ID_SFP1,
  CHIP_ID_SFP2,
  CHIP_ID_SI5324,
  CHIP_ID_INA_0,
  CHIP_ID_INA_1,
  CHIP_ID_XR77129,
  CHIP_ID_LM75AIM_0,
  CHIP_ID_LM75AIM_1,
  CHIP_ID_LM75AIM_2,
  CHIP_ID_LM75AIM_3,
  CHIP_ID_EEPROM,
  CHIP_ID_EEPROM_ID,
  CHIP_ID_MAX6642,


#ifdef MODULE_RTM
  /* Chips on RTM */
  CHIP_ID_RTM_TCA9548,
  CHIP_ID_RTM_EEPROM,
  CHIP_ID_RTM_EEPROM_ID,
  CHIP_ID_RTM_LM75_0,
  CHIP_ID_RTM_LM75_1,
  CHIP_ID_RTM_MAX6642,
  CHIP_ID_RTM_PCF8574A,

  /* Chips on RTM behind MUX */
  CHIP_ID_RTM_MEZ0_EEPROM,
  CHIP_ID_RTM_MEZ0_EEPROM_ID,
  CHIP_ID_RTM_MEZ0_ADT7420,

  CHIP_ID_RTM_MEZ1_EEPROM,
  CHIP_ID_RTM_MEZ1_EEPROM_ID,
  CHIP_ID_RTM_MEZ1_ADT7420,

  CHIP_ID_RTM_SI5324,

  CHIP_ID_RTM_TMP_ADT_1,
  CHIP_ID_RTM_TMP_ADT_2,

  CHIP_ID_RTM_XR77129,
#endif
  I2C_CHIP_CNT
};

#define I2C_MUX_CNT    2

extern i2c_mux_state_t i2c_mux[I2C_MUX_CNT];
extern i2c_bus_mapping_t i2c_bus_map[I2C_BUS_CNT];
extern i2c_chip_mapping_t i2c_chip_map[I2C_CHIP_CNT];

#endif
