name: Build for all targets
on:
  push:
    branches:
      - master
      - devel
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lnls-dig/openmmc-builder:latest
    strategy:
      matrix:
        build-flags:
          - { flags: -DBOARD=afc -DVERSION=3.1 -DBOARD_RTM=8sfp }
          - { flags: -DBOARD=afc -DVERSION=4.0 -DBOARD_RTM=lamp}
          - { flags: -DBOARD=afc -DVERSION=4.0 -DBOARD_RTM=lamp -DDEBUG_PROBE=jlink -DOPENOCD_TRANSPORT=swd }
          - { flags: -DBOARD=afc -DVERSION=4.0 -DBOARD_RTM=lamp -DDEBUG_PROBE=cmsis-dap -DOPENOCD_TRANSPORT=swd }
          - { flags: -DBOARD=afc -DVERSION=4.0 -DBOARD_RTM=lamp -DDEBUG_PROBE=digilent_jtag_hs3 -DOPENOCD_TRANSPORT=jtag }
          - { flags: -DBOARD=afc -DVERSION=4.0 -DBOARD_RTM=lamp -DDEBUG_PROBE=xvc -DOPENOCD_TRANSPORT=jtag -DXVC_HOST=host -DXVC_PORT=0000}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create build environment
        run: mkdir build
      - name: Configure CMake
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ${{matrix.build-flags.flags}}
      - name: Build for all targets
        working-directory: build
        run: make
